// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfCABYzRkMvSeMIIoEvl0KwwTtfbkbF48',
    appId: '1:684172807352:web:bf1b0d28e5d47c36be384d',
    messagingSenderId: '684172807352',
    projectId: 'goldenpark-smart-resident',
    authDomain: 'goldenpark-smart-resident.firebaseapp.com',
    storageBucket: 'goldenpark-smart-resident.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnR_LQdY5NcOmdsV9t5OJuOd3IXoL-TVY',
    appId: '1:684172807352:android:42543c2549b8cb41be384d',
    messagingSenderId: '684172807352',
    projectId: 'goldenpark-smart-resident',
    storageBucket: 'goldenpark-smart-resident.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfaVhlDlFShY_EJH4nuhA2UrkD0Hdrts',
    appId: '1:684172807352:ios:535a6e9f907f8f78be384d',
    messagingSenderId: '684172807352',
    projectId: 'goldenpark-smart-resident',
    storageBucket: 'goldenpark-smart-resident.firebasestorage.app',
    iosBundleId: 'com.example.goldenparkSmartResident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfaVhlDlFShY_EJH4nuhA2UrkD0Hdrts',
    appId: '1:684172807352:ios:535a6e9f907f8f78be384d',
    messagingSenderId: '684172807352',
    projectId: 'goldenpark-smart-resident',
    storageBucket: 'goldenpark-smart-resident.firebasestorage.app',
    iosBundleId: 'com.example.goldenparkSmartResident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfCABYzRkMvSeMIIoEvl0KwwTtfbkbF48',
    appId: '1:684172807352:web:0239adb4c628677bbe384d',
    messagingSenderId: '684172807352',
    projectId: 'goldenpark-smart-resident',
    authDomain: 'goldenpark-smart-resident.firebaseapp.com',
    storageBucket: 'goldenpark-smart-resident.firebasestorage.app',
  );
}
